name: Run CI - Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run_make_ci_format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - uses: ./.github/actions/setup-build-env
        with:
          build_cache_key_name: 'solana-ci-test-v001'
          rust_toolchain_release: stable

      - run: make ci-test
        shell: bash
